apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: sample-boot-knative
spec:
  serviceAccountName: build
  source:
    git:
      url: https://github.com/igayoso/sample-boot-knative
      revision: master
  template:
    name: kaniko
    arguments:
    - name: IMAGE
      value: algo.azurecr.io/sample-boot-knative
      imagePullAlways: true