apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: sample-boot-knative-service
  namespace: default
spec:
  release:
    revisions: ["sample-boot-knative-service-9c4hm", "sample-boot-knative-service-fhpdj"]
    rolloutPercent: 20
    configuration:
      revisionTemplate:
        spec:
          serviceAccountName: build
          container:
            image: algo.azurecr.io/sample-boot-knative:latest