apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: sample-boot-knative-service
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          serviceAccountName: build
          container:
            image: bijukunjummen/sample-boot-knative-app:0.0.3-SNAPSHOT